[package]
name = "bmapconv"
version = "1.0.0"
edition = "2021"
description = "BitMap(64位)轉換工具"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
lazy_static = "1.4"
structopt = "0.3"
colored = "2.0"
